# Generated by Django 5.2.8 on 2026-06-24 11:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientprofile",
            options={
                "ordering": ["full_name"],
                "verbose_name": "پرونده مشتری",
                "verbose_name_plural": "پرونده\u200cهای مشتریان",
            },
        ),
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "ordering": ["-issue_date", "-created_at"],
                "verbose_name": "فاکتور",
                "verbose_name_plural": "فاکتورها",
            },
        ),
        migrations.AlterModelOptions(
            name="invoicelineitem",
            options={
                "ordering": ["created_at"],
                "verbose_name": "ردیف فاکتور",
                "verbose_name_plural": "ردیف\u200cهای فاکتور",
            },
        ),
        migrations.AlterModelOptions(
            name="operationsauditlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "گزارش عملیات",
                "verbose_name_plural": "گزارش\u200cهای عملیات",
            },
        ),
        migrations.AlterModelOptions(
            name="smslog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "گزارش پیامک",
                "verbose_name_plural": "گزارش\u200cهای پیامک",
            },
        ),
        migrations.AlterModelOptions(
            name="smstemplate",
            options={
                "ordering": ["code"],
                "verbose_name": "قالب پیامک",
                "verbose_name_plural": "قالب\u200cهای پیامک",
            },
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="address",
            field=models.TextField(blank=True, verbose_name="آدرس"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="city",
            field=models.CharField(blank=True, max_length=128, verbose_name="شهر"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_clients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ثبت\u200cکننده",
            ),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="deceased_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="نام مرحوم/مرحومه"
            ),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="نام کامل مشتری"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="شناسه",
            ),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="memorial_date",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="تاریخ مراسم"
            ),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="memorial_location",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="محل مراسم"
            ),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="notes",
            field=models.TextField(blank=True, verbose_name="یادداشت داخلی"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="phone",
            field=models.CharField(
                db_index=True,
                max_length=32,
                validators=[
                    django.core.validators.RegexValidator(
                        "^09\\d{9}$", "شماره موبایل باید با فرمت 09xxxxxxxxx باشد."
                    )
                ],
                verbose_name="شماره موبایل",
            ),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="province",
            field=models.CharField(blank=True, max_length=128, verbose_name="استان"),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="operations.clientprofile",
                verbose_name="مشتری",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_invoices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ثبت\u200cکننده",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="discount_amount",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="مبلغ تخفیف",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="مهلت پرداخت"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="fee_amount",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="هزینه اضافه",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="شناسه",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=32,
                unique=True,
                verbose_name="شماره فاکتور",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="issue_date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="تاریخ صدور"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="notes",
            field=models.TextField(blank=True, verbose_name="یادداشت"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "پیش\u200cنویس"),
                    ("sent", "ارسال\u200cشده"),
                    ("paid", "پرداخت\u200cشده"),
                    ("cancelled", "لغوشده"),
                ],
                default="draft",
                max_length=16,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="subtotal_amount",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="جمع جزء",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="tax_amount",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="مالیات",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_amount",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="مبلغ نهایی",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="description",
            field=models.CharField(max_length=255, verbose_name="شرح"),
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="discount_amount",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="تخفیف ردیف",
            ),
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="شناسه",
            ),
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="operations.invoice",
                verbose_name="فاکتور",
            ),
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="تعداد",
            ),
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="unit_price",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="قیمت واحد",
            ),
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="operationsauditlog",
            name="action",
            field=models.CharField(max_length=64, verbose_name="عملیات"),
        ),
        migrations.AlterField(
            model_name="operationsauditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operations_audit_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر انجام\u200cدهنده",
            ),
        ),
        migrations.AlterField(
            model_name="operationsauditlog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
        ),
        migrations.AlterField(
            model_name="operationsauditlog",
            name="entity_id",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="شناسه رکورد"
            ),
        ),
        migrations.AlterField(
            model_name="operationsauditlog",
            name="entity_type",
            field=models.CharField(max_length=64, verbose_name="نوع رکورد"),
        ),
        migrations.AlterField(
            model_name="operationsauditlog",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="شناسه",
            ),
        ),
        migrations.AlterField(
            model_name="operationsauditlog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, verbose_name="جزئیات"),
        ),
        migrations.AlterField(
            model_name="smslog",
            name="body",
            field=models.TextField(verbose_name="متن پیام"),
        ),
        migrations.AlterField(
            model_name="smslog",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sms_logs",
                to="operations.clientprofile",
                verbose_name="مشتری",
            ),
        ),
        migrations.AlterField(
            model_name="smslog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
        ),
        migrations.AlterField(
            model_name="smslog",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="پیام خطا"),
        ),
        migrations.AlterField(
            model_name="smslog",
            name="event_type",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="نوع رویداد"
            ),
        ),
        migrations.AlterField(
            model_name="smslog",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="شناسه",
            ),
        ),
        migrations.AlterField(
            model_name="smslog",
            name="provider",
            field=models.CharField(
                default="kavenegar", max_length=32, verbose_name="ارائه\u200cدهنده"
            ),
        ),
        migrations.AlterField(
            model_name="smslog",
            name="provider_message_id",
            field=models.CharField(
                blank=True,
                max_length=128,
                verbose_name="شناسه پیام در سرویس\u200cدهنده",
            ),
        ),
        migrations.AlterField(
            model_name="smslog",
            name="provider_response",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="پاسخ سرویس\u200cدهنده"
            ),
        ),
        migrations.AlterField(
            model_name="smslog",
            name="recipient",
            field=models.CharField(max_length=32, verbose_name="گیرنده"),
        ),
        migrations.AlterField(
            model_name="smslog",
            name="sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="زمان ارسال"
            ),
        ),
        migrations.AlterField(
            model_name="smslog",
            name="sent_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_sms_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ارسال\u200cکننده",
            ),
        ),
        migrations.AlterField(
            model_name="smslog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار"),
                    ("sent", "ارسال\u200cشده"),
                    ("failed", "ناموفق"),
                ],
                default="pending",
                max_length=16,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="smslog",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="operations.smstemplate",
                verbose_name="قالب پیامک",
            ),
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="body",
            field=models.TextField(verbose_name="متن پیامک"),
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="code",
            field=models.CharField(
                choices=[
                    ("fortieth_day", "یادآوری چهلم"),
                    ("anniversary_day", "یادآوری سالگرد"),
                    ("manual", "دستی"),
                ],
                max_length=32,
                unique=True,
                verbose_name="کد قالب",
            ),
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="شناسه",
            ),
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="title",
            field=models.CharField(max_length=255, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
        ),
    ]
