server {
    listen 80;
    listen [::]:80;
    server_name majlesyar.com ir-origin.majlesyar.com global-origin.majlesyar.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name majlesyar.com ir-origin.majlesyar.com global-origin.majlesyar.com;

    ssl_certificate /etc/letsencrypt/live/majlesyar.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/majlesyar.com/privkey.pem;
    ssl_session_timeout 1d;
    ssl_session_cache shared:MajlesyarSSL:10m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    add_header Strict-Transport-Security "max-age=63072000" always;
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options DENY always;
    add_header Referrer-Policy same-origin always;

    client_max_body_size 32m;

    location /api/docs/ {
        include /etc/nginx/snippets/majlesyar-admin-allowlist.conf;
        proxy_pass http://127.0.0.1:8000;
        include /etc/nginx/snippets/majlesyar-proxy.conf;
    }

    location /majmanage/ {
        include /etc/nginx/snippets/majlesyar-admin-allowlist.conf;
        proxy_pass http://127.0.0.1:8000;
        include /etc/nginx/snippets/majlesyar-proxy.conf;
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
        include /etc/nginx/snippets/majlesyar-proxy.conf;
    }
}
