from django.urls import path

from .views import (
    AdminBuilderItemDetailAPIView,
    AdminBuilderItemListCreateAPIView,
    AdminCategoryDetailAPIView,
    AdminCategoryListCreateAPIView,
    AdminCustomerReviewDetailAPIView,
    AdminCustomerReviewListCreateAPIView,
    AdminPagePreviewTargetListAPIView,
    AdminPageProductPlacementListAPIView,
    AdminPageProductPlacementReorderAPIView,
    AdminProductDetailAPIView,
    AdminProductListCreateAPIView,
    AdminTagDetailAPIView,
    AdminTagListCreateAPIView,
    BuilderItemListAPIView,
    CategoryListAPIView,
    CustomerReviewListAPIView,
    PageProductPreviewAPIView,
    ProductDetailAPIView,
    ProductListAPIView,
    TagListAPIView,
)

urlpatterns = [
    path("categories/", CategoryListAPIView.as_view(), name="category-list"),
    path("tags/", TagListAPIView.as_view(), name="tag-list"),
    path("reviews/", CustomerReviewListAPIView.as_view(), name="customer-review-list"),
    path("products/", ProductListAPIView.as_view(), name="product-list"),
    path("products/<str:lookup>/", ProductDetailAPIView.as_view(), name="product-detail"),
    path("page-product-preview/", PageProductPreviewAPIView.as_view(), name="page-product-preview"),
    path("builder-items/", BuilderItemListAPIView.as_view(), name="builder-item-list"),
    path("admin/categories/", AdminCategoryListCreateAPIView.as_view(), name="admin-category-list-create"),
    path("admin/categories/<uuid:id>/", AdminCategoryDetailAPIView.as_view(), name="admin-category-detail"),
    path("admin/tags/", AdminTagListCreateAPIView.as_view(), name="admin-tag-list-create"),
    path("admin/tags/<uuid:id>/", AdminTagDetailAPIView.as_view(), name="admin-tag-detail"),
    path("admin/builder-items/", AdminBuilderItemListCreateAPIView.as_view(), name="admin-builder-item-list-create"),
    path("admin/builder-items/<uuid:id>/", AdminBuilderItemDetailAPIView.as_view(), name="admin-builder-item-detail"),
    path("admin/products/", AdminProductListCreateAPIView.as_view(), name="admin-product-list-create"),
    path("admin/products/<uuid:id>/", AdminProductDetailAPIView.as_view(), name="admin-product-detail"),
    path("admin/reviews/", AdminCustomerReviewListCreateAPIView.as_view(), name="admin-customer-review-list-create"),
    path("admin/reviews/<uuid:id>/", AdminCustomerReviewDetailAPIView.as_view(), name="admin-customer-review-detail"),
    path("admin/page-product-targets/", AdminPagePreviewTargetListAPIView.as_view(), name="admin-page-product-targets"),
    path("admin/page-product-placements/", AdminPageProductPlacementListAPIView.as_view(), name="admin-page-product-placements"),
    path("admin/page-product-placements/reorder/", AdminPageProductPlacementReorderAPIView.as_view(), name="admin-page-product-placements-reorder"),
]
