# Generated by Django 6.0.2 on 2026-02-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_builderitem_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_alt',
            field=models.CharField(blank=True, default='', help_text='راهنما: یک توضیح کوتاه و دقیق برای تصویر بنویسید تا در دسترس پذیری و سئو استفاده شود.', max_length=255, verbose_name='متن جایگزین تصویر (Alt)'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_name',
            field=models.CharField(blank=True, default='', help_text='راهنما: یک نام خوانا برای تصویر وارد کنید (مثال: pak-terhim-luxury). این فیلد برای مدیریت بهتر تصاویر است.', max_length=255, verbose_name='نام تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='راهنما: تصویر محصول را با کیفیت مناسب بارگذاری کنید. می توانید با گزینه پاک کردن، انتخاب تصویر را حذف کنید.', null=True, upload_to='products/', verbose_name='تصویر محصول'),
        ),
    ]
