# Generated by Codex on 2026-02-20

from django.db import migrations


EVENT_CATEGORIES = (
    ("conference", "حلوا", "🍮"),
    ("memorial", "پک ترحیم", "🕯️"),
    ("defense", "???? ? ????", "??"),
    ("party", "تولد/مهمانی", "🎂"),
)


def sync_event_categories(apps, schema_editor):
    Category = apps.get_model("catalog", "Category")
    Product = apps.get_model("catalog", "Product")

    categories_by_slug = {}
    for slug, name, icon in EVENT_CATEGORIES:
        category, _ = Category.objects.update_or_create(
            slug=slug,
            defaults={
                "name": name,
                "icon": icon,
            },
        )
        categories_by_slug[slug] = category

    for product in Product.objects.all():
        event_types = product.event_types or []
        if not isinstance(event_types, list):
            continue

        related_categories = [
            categories_by_slug[slug] for slug in event_types if slug in categories_by_slug
        ]
        if related_categories:
            product.categories.add(*related_categories)


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_product_image_alt_product_image_name_and_more"),
    ]

    operations = [
        migrations.RunPython(sync_event_categories, migrations.RunPython.noop),
    ]
