# Generated by Django 6.0.3 on 2026-03-30 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_tag_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builderitem',
            name='image',
            field=models.ImageField(blank=True, help_text='نکته: بارگذاری تصویر با فرمت\u200cهای jpg، jpeg، png یا webp برای نمایش بهتر این آیتم.', null=True, upload_to='builder-items/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp'))], verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='راهنما: تصویر محصول را با کیفیت مناسب و فرمت\u200cهای jpg، jpeg، png یا webp بارگذاری کنید. می توانید با گزینه پاک کردن، انتخاب تصویر را حذف کنید.', null=True, upload_to='products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp'))], verbose_name='تصویر محصول'),
        ),
    ]
