# Generated by Codex on 2026-04-03

from django.db import migrations, models

import catalog.image_utils


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_alter_builderitem_image_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="نکته: کد رنگ (مثال: #F1C40F یا bg-primary/20).",
                max_length=64,
                verbose_name="رنگ",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="راهنما: لوگو دسته بندی را با فرمت jpg، jpeg، png یا webp بارگذاری کنید.",
                null=True,
                upload_to="category-logos/",
                validators=[catalog.image_utils.image_extension_validator],
                verbose_name="لوگو",
            ),
        ),
    ]
