# Generated by Django 5.2.8 on 2026-04-22 22:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_add_avif_support"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageProductPlacement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="این شناسه به‌صورت خودکار ساخته می‌شود.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="شناسه",
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("home", "صفحه اصلی"),
                            ("shop", "فروشگاه"),
                            ("event", "صفحه مراسم"),
                        ],
                        help_text="مشخص می‌کند این محصول در کدام نوع صفحه مرتب شده است.",
                        max_length=24,
                        verbose_name="نوع صفحه",
                    ),
                ),
                (
                    "page_slug",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="برای صفحه‌های رویداد، اسلاگ رویداد و برای صفحه‌های ثابت کلید داخلی صفحه ذخیره می‌شود.",
                        max_length=128,
                        verbose_name="شناسه صفحه",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="عدد کوچکتر یعنی نمایش زودتر در همان صفحه.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="ترتیب نمایش",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="آخرین به‌روزرسانی")),
                (
                    "product",
                    models.ForeignKey(
                        help_text="محصولی که در این صفحه نمایش داده می‌شود.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_placements",
                        to="catalog.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "چیدمان محصول در صفحه",
                "verbose_name_plural": "چیدمان محصولات در صفحه‌ها",
                "ordering": ["page_type", "page_slug", "position", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("page_type", "page_slug", "product"),
                        name="unique_page_product_placement",
                    )
                ],
            },
        ),
    ]
