# Generated by Django 5.2.8 on 2026-04-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_pageproductplacement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="نکته: کد رنگ را وارد کنید (مثال: #F1C40F یا bg-primary/20).",
                max_length=64,
                verbose_name="رنگ",
            ),
        ),
    ]
