# Generated by Django 5.2.8 on 2026-04-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_alter_category_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_variants",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Automatically generated AVIF, WebP, JPEG, and original backup metadata for responsive delivery.",
                verbose_name="Image variants",
            ),
        ),
    ]
