# Generated by Django 5.2.8 on 2026-06-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_customerreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_variants",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="اطلاعات نسخه\u200cهای AVIF، WebP، JPEG و فایل اصلی برای نمایش سریع\u200cتر و واکنش\u200cگرا.",
                verbose_name="نسخه\u200cهای بهینه تصویر",
            ),
        ),
    ]
