# Generated by Django 6.0.7 on 2026-08-21 09:31

import catalog.image_utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0018_product_is_temporary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="راهنما: تصویر محصول را با کیفیت مناسب و فرمت\u200cهای jpg، jpeg، png، webp یا avif بارگذاری کنید. می توانید با گزینه پاک کردن، انتخاب تصویر را حذف کنید.",
                max_length=500,
                null=True,
                storage=catalog.image_utils.ProductImageStorage(),
                upload_to=catalog.image_utils.build_product_image_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("jpg", "jpeg", "png", "webp", "avif")
                    )
                ],
                verbose_name="تصویر محصول",
            ),
        ),
    ]
