# Generated by Django 6.0.7 on 2026-09-21 22:02

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0024_seed_managed_internal_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="builderitem",
            name="photo_analysis",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="خروجی تحلیل خودکار تصویر و مشخصات آیتم ذخیره\u200cشده روی سرور.",
                verbose_name="نتیجه تحلیل تصویر",
            ),
        ),
        migrations.AlterField(
            model_name="builderitem",
            name="model_3d_status",
            field=models.CharField(
                choices=[
                    ("queued", "در صف ساخت"),
                    ("missing", "ساخته نشده"),
                    ("processing", "در حال ساخت"),
                    ("ready", "آماده"),
                    ("failed", "خطا در ساخت"),
                ],
                default="missing",
                max_length=20,
                verbose_name="وضعیت مدل سه\u200cبعدی",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="model_3d_status",
            field=models.CharField(
                choices=[
                    ("queued", "در صف ساخت"),
                    ("missing", "ساخته نشده"),
                    ("processing", "در حال ساخت"),
                    ("ready", "آماده"),
                    ("failed", "خطا در ساخت"),
                ],
                default="missing",
                max_length=20,
                verbose_name="وضعیت مدل سه\u200cبعدی",
            ),
        ),
        migrations.CreateModel(
            name="AssetProcessingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("product", "محصول"),
                            ("builder_item", "آیتم سازنده پک"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_id", models.UUIDField()),
                ("source_image_name", models.CharField(max_length=500)),
                ("source_sha256", models.CharField(max_length=64)),
                ("request_sha256", models.CharField(max_length=64)),
                ("requested_actions", models.JSONField(blank=True, default=list)),
                ("input_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در صف"),
                            ("running", "در حال پردازش"),
                            ("succeeded", "موفق"),
                            ("failed", "ناموفق"),
                            ("superseded", "جایگزین شده"),
                            ("skipped", "رد شده"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "available_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "وظیفه پردازش تصویر",
                "verbose_name_plural": "وظایف پردازش تصاویر",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "available_at"],
                        name="asset_job_status_available",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"], name="asset_job_target"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target_type", "target_id", "request_sha256"),
                        name="unique_asset_processing_request",
                    )
                ],
            },
        ),
    ]
