# Generated by Django 6.0.7 on 2026-09-22 20:56

import catalog.image_utils
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0025_builderitem_photo_analysis_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductGalleryImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="شناسه",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="عکس دیگری از محصول با فرمت jpg، jpeg، png، webp یا avif.",
                        max_length=500,
                        storage=catalog.image_utils.ProductImageStorage(),
                        upload_to=catalog.image_utils.build_product_gallery_image_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=(
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "webp",
                                    "avif",
                                )
                            )
                        ],
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "image_alt",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="اگر خالی باشد، از نام فایل ساخته می\u200cشود.",
                        max_length=255,
                        verbose_name="متن جایگزین تصویر (Alt)",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="عدد کوچک\u200cتر زودتر نمایش داده می\u200cشود.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="ترتیب نمایش",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="catalog.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر بیشتر محصول",
                "verbose_name_plural": "تصاویر بیشتر محصول",
                "ordering": ["display_order", "created_at"],
            },
        ),
    ]
