# Generated by Django 5.2.8 on 2026-04-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="telegrambotauditlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Telegram bot audit log",
                "verbose_name_plural": "Telegram bot audit logs",
            },
        ),
        migrations.AlterModelOptions(
            name="telegrambotstate",
            options={
                "ordering": ["key"],
                "verbose_name": "Telegram bot state",
                "verbose_name_plural": "Telegram bot states",
            },
        ),
        migrations.AlterModelOptions(
            name="telegramconfirmation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Telegram confirmation",
                "verbose_name_plural": "Telegram confirmations",
            },
        ),
        migrations.AlterModelOptions(
            name="telegramoperator",
            options={
                "ordering": ["telegram_user_id"],
                "verbose_name": "Telegram operator",
                "verbose_name_plural": "Telegram operators",
            },
        ),
        migrations.AlterModelOptions(
            name="telegramupdatereceipt",
            options={
                "ordering": ["-update_id"],
                "verbose_name": "Telegram update receipt",
                "verbose_name_plural": "Telegram update receipts",
            },
        ),
    ]
