# Generated by Django 5.2.8 on 2026-06-24 11:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0002_alter_telegrambotauditlog_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="telegrambotauditlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "گزارش ربات تلگرام",
                "verbose_name_plural": "گزارش\u200cهای ربات تلگرام",
            },
        ),
        migrations.AlterModelOptions(
            name="telegrambotstate",
            options={
                "ordering": ["key"],
                "verbose_name": "وضعیت ربات تلگرام",
                "verbose_name_plural": "وضعیت\u200cهای ربات تلگرام",
            },
        ),
        migrations.AlterModelOptions(
            name="telegramconfirmation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "تأیید تلگرام",
                "verbose_name_plural": "تأییدهای تلگرام",
            },
        ),
        migrations.AlterModelOptions(
            name="telegramoperator",
            options={
                "ordering": ["telegram_user_id"],
                "verbose_name": "اپراتور تلگرام",
                "verbose_name_plural": "اپراتورهای تلگرام",
            },
        ),
        migrations.AlterModelOptions(
            name="telegramupdatereceipt",
            options={
                "ordering": ["-update_id"],
                "verbose_name": "دریافت پیام تلگرام",
                "verbose_name_plural": "دریافت\u200cهای پیام تلگرام",
            },
        ),
        migrations.AlterField(
            model_name="telegrambotauditlog",
            name="action",
            field=models.CharField(blank=True, max_length=128, verbose_name="عملیات"),
        ),
        migrations.AlterField(
            model_name="telegrambotauditlog",
            name="command",
            field=models.CharField(max_length=128, verbose_name="دستور"),
        ),
        migrations.AlterField(
            model_name="telegrambotauditlog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
        ),
        migrations.AlterField(
            model_name="telegrambotauditlog",
            name="django_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="telegram_bot_audit_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر پنل",
            ),
        ),
        migrations.AlterField(
            model_name="telegrambotauditlog",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="پیام خطا"),
        ),
        migrations.AlterField(
            model_name="telegrambotauditlog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, verbose_name="جزئیات"),
        ),
        migrations.AlterField(
            model_name="telegrambotauditlog",
            name="new_state",
            field=models.JSONField(blank=True, null=True, verbose_name="وضعیت جدید"),
        ),
        migrations.AlterField(
            model_name="telegrambotauditlog",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="telegram_bot.telegramoperator",
                verbose_name="اپراتور",
            ),
        ),
        migrations.AlterField(
            model_name="telegrambotauditlog",
            name="previous_state",
            field=models.JSONField(blank=True, null=True, verbose_name="وضعیت قبلی"),
        ),
        migrations.AlterField(
            model_name="telegrambotauditlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "موفق"),
                    ("denied", "ردشده"),
                    ("failed", "ناموفق"),
                    ("ignored", "نادیده\u200cگرفته\u200cشده"),
                    ("pending", "در انتظار"),
                ],
                default="success",
                max_length=16,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="telegrambotauditlog",
            name="target_identifier",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="شناسه هدف"
            ),
        ),
        migrations.AlterField(
            model_name="telegrambotauditlog",
            name="target_type",
            field=models.CharField(blank=True, max_length=128, verbose_name="نوع هدف"),
        ),
        migrations.AlterField(
            model_name="telegrambotauditlog",
            name="telegram_chat_id",
            field=models.BigIntegerField(
                blank=True, db_index=True, null=True, verbose_name="شناسه گفتگو تلگرام"
            ),
        ),
        migrations.AlterField(
            model_name="telegrambotauditlog",
            name="telegram_user_id",
            field=models.BigIntegerField(
                blank=True, db_index=True, null=True, verbose_name="شناسه کاربر تلگرام"
            ),
        ),
        migrations.AlterField(
            model_name="telegrambotstate",
            name="key",
            field=models.CharField(max_length=128, unique=True, verbose_name="کلید"),
        ),
        migrations.AlterField(
            model_name="telegrambotstate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="telegrambotstate",
            name="value",
            field=models.JSONField(blank=True, default=dict, verbose_name="مقدار"),
        ),
        migrations.AlterField(
            model_name="telegramconfirmation",
            name="action",
            field=models.CharField(max_length=128, verbose_name="عملیات"),
        ),
        migrations.AlterField(
            model_name="telegramconfirmation",
            name="audit_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmations",
                to="telegram_bot.telegrambotauditlog",
                verbose_name="گزارش مرتبط",
            ),
        ),
        migrations.AlterField(
            model_name="telegramconfirmation",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="زمان لغو"),
        ),
        migrations.AlterField(
            model_name="telegramconfirmation",
            name="command",
            field=models.CharField(blank=True, max_length=128, verbose_name="دستور"),
        ),
        migrations.AlterField(
            model_name="telegramconfirmation",
            name="consumed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="زمان استفاده"
            ),
        ),
        migrations.AlterField(
            model_name="telegramconfirmation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
        ),
        migrations.AlterField(
            model_name="telegramconfirmation",
            name="expires_at",
            field=models.DateTimeField(verbose_name="زمان انقضا"),
        ),
        migrations.AlterField(
            model_name="telegramconfirmation",
            name="operator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="confirmations",
                to="telegram_bot.telegramoperator",
                verbose_name="اپراتور",
            ),
        ),
        migrations.AlterField(
            model_name="telegramconfirmation",
            name="payload",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="داده\u200cها"
            ),
        ),
        migrations.AlterField(
            model_name="telegramconfirmation",
            name="target_identifier",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="شناسه هدف"
            ),
        ),
        migrations.AlterField(
            model_name="telegramconfirmation",
            name="target_type",
            field=models.CharField(blank=True, max_length=128, verbose_name="نوع هدف"),
        ),
        migrations.AlterField(
            model_name="telegramconfirmation",
            name="telegram_chat_id",
            field=models.BigIntegerField(
                db_index=True, verbose_name="شناسه گفتگو تلگرام"
            ),
        ),
        migrations.AlterField(
            model_name="telegramconfirmation",
            name="telegram_user_id",
            field=models.BigIntegerField(
                db_index=True, verbose_name="شناسه کاربر تلگرام"
            ),
        ),
        migrations.AlterField(
            model_name="telegramconfirmation",
            name="token",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="توکن تأیید",
            ),
        ),
        migrations.AlterField(
            model_name="telegramoperator",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
        ),
        migrations.AlterField(
            model_name="telegramoperator",
            name="django_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="telegram_operators",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر پنل",
            ),
        ),
        migrations.AlterField(
            model_name="telegramoperator",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="telegramoperator",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="telegramoperator",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="نام خانوادگی"
            ),
        ),
        migrations.AlterField(
            model_name="telegramoperator",
            name="last_seen_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="آخرین بازدید"
            ),
        ),
        migrations.AlterField(
            model_name="telegramoperator",
            name="notifications_enabled",
            field=models.BooleanField(default=True, verbose_name="دریافت اعلان"),
        ),
        migrations.AlterField(
            model_name="telegramoperator",
            name="telegram_chat_id",
            field=models.BigIntegerField(
                blank=True, db_index=True, null=True, verbose_name="شناسه گفتگو تلگرام"
            ),
        ),
        migrations.AlterField(
            model_name="telegramoperator",
            name="telegram_user_id",
            field=models.BigIntegerField(
                db_index=True, unique=True, verbose_name="شناسه کاربر تلگرام"
            ),
        ),
        migrations.AlterField(
            model_name="telegramoperator",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="telegramoperator",
            name="username",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="نام کاربری"
            ),
        ),
        migrations.AlterField(
            model_name="telegramupdatereceipt",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="پیام خطا"),
        ),
        migrations.AlterField(
            model_name="telegramupdatereceipt",
            name="payload",
            field=models.JSONField(blank=True, default=dict, verbose_name="داده خام"),
        ),
        migrations.AlterField(
            model_name="telegramupdatereceipt",
            name="processed_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="زمان پردازش"),
        ),
        migrations.AlterField(
            model_name="telegramupdatereceipt",
            name="source",
            field=models.CharField(
                default="webhook", max_length=32, verbose_name="منبع"
            ),
        ),
        migrations.AlterField(
            model_name="telegramupdatereceipt",
            name="status",
            field=models.CharField(
                choices=[
                    ("processed", "پردازش\u200cشده"),
                    ("failed", "ناموفق"),
                    ("ignored", "نادیده\u200cگرفته\u200cشده"),
                ],
                default="processed",
                max_length=16,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="telegramupdatereceipt",
            name="update_id",
            field=models.BigIntegerField(
                db_index=True, unique=True, verbose_name="شناسه آپدیت"
            ),
        ),
    ]
