# Generated by Django 5.2.8 on 2026-06-24 10:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="شناسه",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=140, verbose_name="نام دسته بندی"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=160, unique=True, verbose_name="اسلاگ"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="توضیحات"),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="رنگ"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=100,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="ترتیب نمایش",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "دسته بندی وبلاگ",
                "verbose_name_plural": "دسته بندی های وبلاگ",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BlogTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="شناسه",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="نام تگ")),
                (
                    "slug",
                    models.SlugField(max_length=140, unique=True, verbose_name="اسلاگ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "تگ وبلاگ",
                "verbose_name_plural": "تگ های وبلاگ",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="شناسه",
                    ),
                ),
                ("title", models.CharField(max_length=220, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=220, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, default="", max_length=260, verbose_name="زیرعنوان"
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(blank=True, default="", verbose_name="خلاصه"),
                ),
                ("content", models.TextField(verbose_name="متن مقاله")),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=(
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "webp",
                                    "avif",
                                )
                            )
                        ],
                        verbose_name="تصویر شاخص",
                    ),
                ),
                (
                    "hero_image_alt",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="متن جایگزین تصویر",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش نویس"),
                            ("published", "منتشر شده"),
                            ("archived", "آرشیو شده"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                ("featured", models.BooleanField(default=False, verbose_name="ویژه")),
                (
                    "allow_comments",
                    models.BooleanField(default=True, verbose_name="امکان ثبت دیدگاه"),
                ),
                (
                    "reading_minutes",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                        verbose_name="زمان مطالعه",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد بازدید"),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, default="", max_length=260, verbose_name="عنوان سئو"
                    ),
                ),
                (
                    "seo_description",
                    models.TextField(
                        blank=True, default="", verbose_name="توضیحات سئو"
                    ),
                ),
                (
                    "seo_keywords",
                    models.JSONField(
                        blank=True, default=list, verbose_name="کلمات کلیدی سئو"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان انتشار"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="blog.blogcategory",
                        verbose_name="دسته بندی",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="posts",
                        to="blog.blogtag",
                        verbose_name="تگ ها",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقاله وبلاگ",
                "verbose_name_plural": "مقاله های وبلاگ",
                "ordering": ["-featured", "-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="شناسه",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="نام")),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="ایمیل"
                    ),
                ),
                ("body", models.TextField(verbose_name="متن دیدگاه")),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="تایید شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="blog.blogcomment",
                        verbose_name="پاسخ به",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.blogpost",
                        verbose_name="مقاله",
                    ),
                ),
            ],
            options={
                "verbose_name": "دیدگاه وبلاگ",
                "verbose_name_plural": "دیدگاه های وبلاگ",
                "ordering": ["created_at"],
            },
        ),
    ]
