# Generated by Django 5.2.8 on 2026-06-25 22:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="blogcategory",
            index=models.Index(
                fields=["is_active", "display_order"],
                name="blog_blogca_is_acti_22f456_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="blogcomment",
            index=models.Index(
                fields=["post", "is_approved", "parent", "created_at"],
                name="blog_blogco_post_id_97c10f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["status", "published_at"], name="blog_blogpo_status_aa5436_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["featured", "published_at"],
                name="blog_blogpo_feature_e75a47_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["category", "status", "published_at"],
                name="blog_blogpo_categor_793e94_idx",
            ),
        ),
    ]
