# Generated by Django 6.0.2 on 2026-02-12 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('min_order_qty', models.PositiveIntegerField(default=40, validators=[django.core.validators.MinValueValidator(1)])),
                ('lead_time_hours', models.PositiveIntegerField(default=48, validators=[django.core.validators.MinValueValidator(0)])),
                ('allowed_provinces', models.JSONField(blank=True, default=list)),
                ('delivery_windows', models.JSONField(blank=True, default=list)),
                ('payment_methods', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
