# Generated by Django 6.0.2 on 2026-04-18 15:08

import django.core.validators
import site_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0003_sitesetting_contact_social_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="homepage_benefits_section",
            field=models.JSONField(
                blank=True,
                default=site_settings.models.default_homepage_benefits_section,
                help_text='ساختار پیشنهادی: {"eyebrow": "...", "title": "...", "items": [{"title": "...", "description": "...", "note": "..."}]}',
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="site_top_notice",
            field=models.JSONField(
                blank=True,
                default=site_settings.models.default_site_top_notice,
                help_text='ساختار پیشنهادی: {"title": "...", "message": "...", "badge": "..."}',
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="allowed_provinces",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="delivery_windows",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="id",
            field=models.PositiveSmallIntegerField(
                default=1, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="lead_time_hours",
            field=models.PositiveIntegerField(
                default=48, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="min_order_qty",
            field=models.PositiveIntegerField(
                default=40, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="payment_methods",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
