# Generated by Django 6.0.2 on 2026-04-18 19:40

import django.core.validators
import site_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0004_sitesetting_homepage_benefits_section_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="event_pages",
            field=models.JSONField(
                blank=True,
                default=site_settings.models.default_event_pages,
                help_text='ساختار پیشنهادی: [{"id": "conference", "name": "...", "slug": "...", "description": "...", "seo_title": "...", "seo_description": "...", "seo_keywords": ["..."], "faqs": [{"question": "...", "answer": "..."}], "icon": "🍢", "color": "bg-secondary", "available": true}]',
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="page_seo",
            field=models.JSONField(
                blank=True,
                default=site_settings.models.default_page_seo,
                help_text='ساختار پیشنهادی: {"home": {"title": "...", "description": "...", "keywords": ["..."]}, "shop": {"title": "...", "description": "...", "keywords": ["..."]}}',
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="site_branding",
            field=models.JSONField(
                blank=True,
                default=site_settings.models.default_site_branding,
                help_text='ساختار پیشنهادی: {"site_name": "...", "site_alternate_name": "...", "site_tagline": "...", "logo_alt": "...", "meta_author": "...", "default_meta_title": "...", "default_meta_description": "...", "default_meta_keywords": ["..."], "admin_site_title": "...", "admin_site_header": "...", "admin_site_subheader": "...", "admin_site_symbol": "..."}',
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="site_favicon",
            field=models.ImageField(
                blank=True,
                help_text="آیکن مرورگر و تب سایت. ترجیحاً فایل مربعی و سبک بارگذاری شود.",
                null=True,
                upload_to="site-settings/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("jpg", "jpeg", "png", "webp", "avif")
                    )
                ],
                verbose_name="فاوآیکن سایت",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="site_logo",
            field=models.ImageField(
                blank=True,
                help_text="لوگوی اصلی سایت برای هدر، فوتر و پنل مدیریت.",
                null=True,
                upload_to="site-settings/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("jpg", "jpeg", "png", "webp", "avif")
                    )
                ],
                verbose_name="لوگوی سایت",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="site_og_image",
            field=models.ImageField(
                blank=True,
                help_text="تصویر پیش\u200cفرض شبکه\u200cهای اجتماعی و Open Graph.",
                null=True,
                upload_to="site-settings/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("jpg", "jpeg", "png", "webp", "avif")
                    )
                ],
                verbose_name="تصویر اشتراک\u200cگذاری",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="theme_palette",
            field=models.JSONField(
                blank=True,
                default=site_settings.models.default_theme_palette,
                help_text='ساختار پیشنهادی: {"primary": "#0C9FC7", "accent": "#D6A45B", "background": "#FDFBF7", "surface": "#FFFFFF", "foreground": "#24303A", "muted_foreground": "#5E6B78", "success": "#218A52", "warning": "#C98A10"}',
            ),
        ),
    ]
