# Generated by Django 5.2.8 on 2026-06-24 11:22

import django.core.validators
import site_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0007_update_existing_contact_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesetting",
            name="allowed_provinces",
            field=models.JSONField(
                blank=True, default=list, verbose_name="استان\u200cهای مجاز"
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="bale_url",
            field=models.URLField(
                blank=True,
                default="https://ble.ir/majlesyar",
                max_length=500,
                verbose_name="لینک بله",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="contact_address",
            field=models.TextField(
                blank=True,
                default="تهران، امیرآباد، خیابان کارگر شمالی، خیابان فرشی مقدم(شانزدهم)، پلاک ۹۱، واحد۶.",
                verbose_name="آدرس",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                default="09122148354",
                max_length=32,
                verbose_name="شماره تماس",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="delivery_windows",
            field=models.JSONField(
                blank=True, default=list, verbose_name="بازه\u200cهای تحویل"
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="eitaa_url",
            field=models.URLField(
                blank=True,
                default="https://eitaa.com/majlesyar",
                max_length=500,
                verbose_name="لینک ایتا",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="event_pages",
            field=models.JSONField(
                blank=True,
                default=site_settings.models.default_event_pages,
                help_text='ساختار پیشنهادی: [{"id": "conference", "name": "...", "slug": "...", "description": "...", "seo_title": "...", "seo_description": "...", "seo_keywords": ["..."], "faqs": [{"question": "...", "answer": "..."}], "icon": "🍢", "color": "bg-secondary", "available": true}]',
                verbose_name="صفحات محصول",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="homepage_benefits_section",
            field=models.JSONField(
                blank=True,
                default=site_settings.models.default_homepage_benefits_section,
                help_text='ساختار پیشنهادی: {"eyebrow": "...", "title": "...", "items": [{"title": "...", "description": "...", "note": "..."}]}',
                verbose_name="مزایای صفحه اصلی",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="id",
            field=models.PositiveSmallIntegerField(
                default=1,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="شناسه",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="instagram_url",
            field=models.URLField(
                blank=True,
                default="https://instagram.com/majlesyar",
                max_length=500,
                verbose_name="لینک اینستاگرام",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="lead_time_hours",
            field=models.PositiveIntegerField(
                default=48,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="حداقل زمان آماده\u200cسازی (ساعت)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="maps_embed_url",
            field=models.URLField(
                blank=True,
                default="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3239.9627430068!2d51.4066!3d35.7219!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMzXCsDQzJzE4LjgiTiA1McKwMjQnMjMuOCJF!5e0!3m2!1sen!2s!4v1699999999999!5m2!1sen!2s",
                max_length=1000,
                verbose_name="لینک نمایش نقشه",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="maps_url",
            field=models.URLField(
                blank=True,
                default="https://maps.google.com/?q=Tehran,Valiasr",
                max_length=500,
                verbose_name="لینک نقشه",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="min_order_qty",
            field=models.PositiveIntegerField(
                default=40,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="حداقل تعداد سفارش",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="page_seo",
            field=models.JSONField(
                blank=True,
                default=site_settings.models.default_page_seo,
                help_text='ساختار پیشنهادی: {"home": {"title": "...", "description": "...", "keywords": ["..."]}, "shop": {"title": "...", "description": "...", "keywords": ["..."]}}',
                verbose_name="سئوی صفحات",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="payment_methods",
            field=models.JSONField(
                blank=True, default=list, verbose_name="روش\u200cهای پرداخت"
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="rubika_url",
            field=models.URLField(
                blank=True,
                default="https://rubika.ir/majlesyar",
                max_length=500,
                verbose_name="لینک روبیکا",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="site_branding",
            field=models.JSONField(
                blank=True,
                default=site_settings.models.default_site_branding,
                help_text='ساختار پیشنهادی: {"site_name": "...", "site_alternate_name": "...", "site_tagline": "...", "logo_alt": "...", "meta_author": "...", "default_meta_title": "...", "default_meta_description": "...", "default_meta_keywords": ["..."], "admin_site_title": "...", "admin_site_header": "...", "admin_site_subheader": "...", "admin_site_symbol": "..."}',
                verbose_name="هویت برند و مدیریت",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="site_top_notice",
            field=models.JSONField(
                blank=True,
                default=site_settings.models.default_site_top_notice,
                help_text='ساختار پیشنهادی: {"title": "...", "message": "...", "badge": "..."}',
                verbose_name="اعلان بالای سایت",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="soroush_url",
            field=models.URLField(
                blank=True,
                default="https://splus.ir/majlesyar",
                max_length=500,
                verbose_name="لینک سروش",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="telegram_url",
            field=models.URLField(
                blank=True,
                default="https://t.me/majlesyar",
                max_length=500,
                verbose_name="لینک تلگرام",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="theme_palette",
            field=models.JSONField(
                blank=True,
                default=site_settings.models.default_theme_palette,
                help_text='ساختار پیشنهادی: {"primary": "#00C2F2", "accent": "#00C2F2", "background": "#FAF8F2", "surface": "#F2ECE2", "foreground": "#20262F", "muted_foreground": "#566170", "success": "#218A52", "warning": "#C98A10"}',
                verbose_name="رنگ\u200cهای سایت",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="whatsapp_url",
            field=models.URLField(
                blank=True,
                default="https://wa.me/989122148354",
                max_length=500,
                verbose_name="لینک واتساپ",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="working_hours",
            field=models.CharField(
                blank=True,
                default="شنبه تا پنجشنبه ۹ صبح تا ۹ شب",
                max_length=255,
                verbose_name="ساعت کاری",
            ),
        ),
    ]
