setuid=pdns
setgid=pdns
local-address=0.0.0.0,::
local-port=53
launch=
include-dir=/etc/powerdns/pdns.d
version-string=anonymous
webserver=yes
webserver-address=127.0.0.1
webserver-allow-from=127.0.0.1,::1
api=yes
api-key=replace-me
disable-axfr=yes
edns-subnet-processing=yes
log-dns-details=no
